### ISSUE TITLE
Server Side Script not executing - Custom Application Scope

### ISSUE THREAD

**Issue by kpoornachander** [thewhitespace/Xplore#10]
Tried running a server side script with a custom application selected. Tried to create an object of a class(custom application scoped but accessible Global), the output screen is empty.
Even a gs.print statement results nothing.

**Comment by jneale** [comment]
Hi, are you running the latest version of Xplore? If you are then please let me know your instance version and if the app is a global or scoped app.

**Comment by jneale** [comment]
Closing this as cannot reproduce with latest version.
