### ISSUE TITLE
Jakarta

### ISSUE THREAD

**Issue by binhftw** [thewhitespace/Xplore#12]
Anyone issues with loading Xplore after Jakarta upgrade? I'm getting a blank page now

**Comment by t1mb0b** [comment]
I am running it on Jakarta and Kingston, seems to be working OK. What version are you on? I am running 4.4 (latest)

**Comment by binhftw** [comment]
I got it to work after updating to 4.4. Before Jakarta upgrade we were on
4.2

**Comment by jneale** [comment]
I can confirm there was an issue with the old version of Xplore working with Jakarta. As with all things, please just make sure you're on the latest version! Thanks! :)
