### ISSUE TITLE
Contributing - how do you want this to happen?

### ISSUE THREAD

**Issue by jacebenson** [thewhitespace/Xplore#13]
I was going to add this functionality to this; but not sure what all you expect as the update.  

https://community.servicenow.com/community/develop/blog/2016/06/10/xplore-gliderecord-script-tool

So let me know if just adding the folder/file's to be updated in the /src folder or if you need the xml rebuilt as well.  Thanks!

**Comment by jneale** [comment]
Hey Jace,

Awesome stuff.

Normally I'd say that if you can just update the src folder that would be great - however this one is actually quite trivial so I'll just add it and save you the Git effort! Feel free to add it yourself of course.

Thanks for the reminder about this one!

**Comment by jacebenson** [comment]
I went ahead and just made the pull request, if its not good, no worries.  I'll close this issue though,
