### ISSUE TITLE
Is Xplore tested on Madrid?

### ISSUE THREAD

**Issue by d-oderbolz** [thewhitespace/Xplore#20]
I have successfully installed Xplore on my personal Madrid instance.
But I noticed that Madrid is not mentioned in the compatible versions.
What is the status?

Thanks a lot & Best
Daniel

**Comment by j4rodm** [comment]
I've been running Xplore on Madrid for months without any noticeable issues. I'm sure it will get updated after someone does some official regression testing.

**Comment by jneale** [comment]
It is tested on all current releases. I've updated the Readme and Share to reflect that this is valid for Madrid.
