### ISSUE TITLE
Madrid integer field - Cannot dotwalk with a non-object: snd_Xplore.ObjectReporter

### ISSUE THREAD

**Issue by MrEnigmamgine** [thewhitespace/Xplore#23]
```
var gr = new GlideRecord('ast_contract');
gr.get('694a509cdb44eb007310f969af96193b');
gs.addInfoMessage(gr.u_autorenewal_advanced_notice_window);

var x = gr.number;
gs.addInfoMessage(x);

// var window = gr.u_autorenewal_advanced_notice_window;
// gs.addInfoMessage(window);
```
When I try to run the above block of code, Xplore will output the correct value.  However, if I uncomment the last two lines I get the following message:

> Exception occured. Error: Cannot dotwalk with a non-object: snd_Xplore.ObjectReporter

The field I'm trying to dot-walk to is an integer field and in this case the expected value is 30.  Dictionary screenshot below:

![8-19 1](https://user-images.githubusercontent.com/1953664/63286359-d0bd0c00-c285-11e9-9d07-41f04d8b7c12.PNG)

I don't understand why Xplore will allow me to dot-walk for the field in line 3, but when I try to store it as a variable in line 8 I get an error.

Edit:  The code runs fine when using the built-in background script solution.

**Comment by jneale** [comment]
Hi,

This is because you are using the variable 'window' which is used by Xplore to determine if it's running client side in your browser rather than on the server. Simply renaming your variable to anything other than 'window' will fix the issue.

Thanks
James
