### ISSUE TITLE
New Feature Request - Call GlideAjax server script

### ISSUE THREAD

**Issue by kev1nme1er** [thewhitespace/Xplore#30]
I know this it is possible to use Ctrl + Shift + Alt + J to test GlideAjax server scripts, but I really prefer Xplore and think others would also benefit from being able to call GlideAjax server scripts from Xplore.  When I try to do it now, I get the error "ReferenceError: GlideAjax is not defined".

**Comment by jneale** [comment]
You can already do this by opening Xplore using the glasses icon and selecting the client frame to run Xplore. On the dropdown that says 'Server', simply choose 'Opener: gsft_main'. If you navigate directly to Xplore via URL then there will be no parent window so this option will not be available.
