### ISSUE TITLE
Xplore doesn't open in Jakarta

### ISSUE THREAD

**Issue by jbgriffith** [thewhitespace/Xplore#9]
I get a new tab that never loads when clicking on the icon or the menu link. I noticed a message in my original tab that says **Error MessageIllegal access to method getImpersonatingUserName in class com.glide.sys.GlideSession**

**Comment by jneale** [comment]
What version of Xplore are you using and on what version of ServiceNow?

**Comment by jbgriffith** [comment]
My mistake, I wasn't updated
